### ISSUE TITLE
deploy error

### ISSUE THREAD

**Issue by moli1987** [devgateway/amp#3340] opened 2020-06-29 07:38 UTC
Hello,
Im trying to deploy amp application on ubuntu server but I get a lot of errors in tomcat logs.
I dont have any amp database backup so I just created one empty database,could this be the problem?
I attached catalina logs so if possible could you check and guide me if I missed some installation step or where should I be searching for errors.
[catalina.zip](https://github.com/devgateway/amp/files/4844409/catalina.zip)

Thank you in advance.

**Comment by jdeanquin-dg** [comment] 2020-07-24 16:04
Hello @moli1987 sorry for the late response. The problem is with the mvn goal you are using. I will update the README with the missing details.
Thanks

**Comment by jdeanquin-dg** [comment] 2021-07-08 12:02
Hello @moli1987 I apologize  for the late late reply. We have fixed a test database and it is committed in develop. That should fix your amp startup
Best

**Closed by jdeanquin-dg** 2021-07-08 12:02 UTC
